### PR TITLE
Replace `fulldim` with `getd` in `extractrow`

### LINKED ISSUE #23: Segmentation fault: 11 related to `extractrow`?
Copy the file [`game1`](https://github.com/JuliaPolyhedra/lrslib/blob/master/game1) from `lrslib` into the current directory.

```jl
julia> using LRSLib

julia> hr1 = LRSLib.HMatrix("game1")

H-representation LRSLib.HMatrix:
1-element iterator of Polyhedra.HyperPlane{Rational{BigInt},Array{Rational{BigInt},1}}:
 HyperPlane(Rational{BigInt}[-1//1, -1//1, -1//1, 0//1], -1//1),
5-element iterator of Polyhedra.HalfSpace{Rational{BigInt},Array{Rational{BigInt},1}}:
 HalfSpace(Rational{BigInt}[-1//1, 0//1, 0//1, 0//1], 0//1)
 HalfSpace(Rational{BigInt}[0//1, -1//1, 0//1, 0//1], 0//1)
 HalfSpace(Rational{BigInt}[0//1, 0//1, -1//1, 0//1], 0//1)
 HalfSpace(Rational{BigInt}[1//1, 0//1, 4//1, -1//1], 0//1)
 HalfSpace(Rational{BigInt}[0//1, 2//1, 3//1, -1//1], 0//1)

julia> extm1 = convert(LRSLib.VMatrix, hr1)
V-representation LRSLib.VMatrix:
5-element iterator of Array{Rational{BigInt},1}:
 Rational{BigInt}[2//3, 1//3, 0//1, 2//3]
 Rational{BigInt}[0//1, 1//3, 2//3, 8//3]
 Rational{BigInt}[0//1, 1//1, 0//1, 2//1]
 Rational{BigInt}[1//1, 0//1, 0//1, 1//1]
 Rational{BigInt}[0//1, 0//1, 1//1, 4//1],
3-element iterator of Polyhedra.Ray{Rational{BigInt},Array{Rational{BigInt},1}}:
 Ray(Rational{BigInt}[0//1, 0//1, 0//1, 1//1])
 Ray(Rational{BigInt}[0//1, 0//1, 0//1, 1//1])
 Ray(Rational{BigInt}[0//1, 0//1, 0//1, 1//1])

julia> LRSLib.MixedMatHRep(hr1)

signal (11): Segmentation fault: 11
in expression starting at no file:0
__gmpn_copyi at /Applications/Julia-1.0.app/Contents/Resources/julia/lib/julia/libgmp.10.dylib (unknown line)
Allocations: 17730755 (Pool: 17729112; Big: 1643); GC: 29
Segmentation fault: 11
```

```jl
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by oyamad**
This fixes #23.

But causes errors at other places...

### CODE REVIEW

**Comment by blegat** [comment]
So this means that when iterating over the elements of a representation of full-dimension `N`, you will get elements of size different to `N`. That violates Polyhedra's definition. Is there are way to recover the point in correct dimension ?
What is LRS doing ? Reducing the space to a lower dimensional one because he found some linearity ?

**Comment by oyamad** [comment]
I do not know what `lrs` does internally.. It seems one column is removed at some point:

```jl
using LRSLib
using LRSLib: @lrs_ccall, Clrs_dic, Clrs_dat

M = Rational{BigInt}[
    0 1 0 0 0
    0 0 1 0 0
    0 0 0 1 0
    0 -1 0 -4 1
    0 0 -2 -3 1
    -1 1 1 1 0
];
m, d = size(M, 1), size(M, 2) - 1;
linearity = BitSet(m);
P, Q = LRSLib.initmatrix(M, linearity, true);
hr0 = LRSLib.HMatrix(d, P, Q)
LRSLib.setdebug(hr0, true)
@lrs_ccall init Clong (Ptr{Cchar},) C_NULL  # Needed for the first time for printing
LRSLib.getfirstbasis(hr0)
```

```
*Starting cobasis uses input row order 6 5 4 3 2 1
 Basis    0 5 6 7 8 9 10  Row 0 1 2 3 4 5 6 
 Co-Basis 1 2 3 4 11  Column 1 2 3 4 0  det= 1 
A[0][1]= 1 [2]= 1 [3]= 1 [4]= 1 [11]= 1 
A[5][1]= 1 [2]= 0 [3]= 0 [4]= 0 [11]= 0 
A[6][1]= 0 [2]= 1 [3]= 0 [4]= 0 [11]= 0 
A[7][1]= 0 [2]= 0 [3]= 1 [4]= 0 [11]= 0 
A[8][1]=-1 [2]= 0 [3]=-4 [4]= 1 [11]= 0 
A[9][1]= 0 [2]=-2 [3]=-3 [4]= 1 [11]= 0 
A[10][1]= 1 [2]= 1 [3]= 1 [4]= 0 [11]=-1 

getabasis from inequalities given in order 6 5 4 3 2 1
 pivot  B[6]=10  C[0]=1 
 Basis    0 5 6 7 8 9 10  Row 0 1 2 3 4 5 6 
 Co-Basis 1 2 3 4 11  Column 1 2 3 4 0  det= 1 
A[0][1]= 0 [2]= 0 [3]= 0 [4]= 0 [11]= 0 
A[5][1]= 1 [2]= 0 [3]= 0 [4]= 0 [11]= 0 
A[6][1]= 0 [2]= 1 [3]= 0 [4]= 0 [11]= 0 
A[7][1]= 0 [2]= 0 [3]= 1 [4]= 0 [11]= 0 
A[8][1]=-1 [2]= 0 [3]=-4 [4]= 1 [11]= 0 
A[9][1]= 0 [2]=-2 [3]=-3 [4]= 1 [11]= 0 
A[10][1]= 1 [2]= 1 [3]= 1 [4]= 0 [11]=-1 
 depth=0 det= 1 
 pivot  B[6]=9  C[0]=2 
 Basis    0 1 5 6 7 8 9  Row 0 6 1 2 3 4 5 
 Co-Basis 2 3 4 10 11  Column 2 3 4 1 0  det= 1 
A[0][2]= 0 [3]= 0 [4]= 0 [10]= 0 [11]= 0 
A[1][2]=-1 [3]=-1 [4]= 0 [10]= 1 [11]= 1 
A[5][2]=-1 [3]=-1 [4]= 0 [10]= 1 [11]= 1 
A[6][2]= 1 [3]= 0 [4]= 0 [10]= 0 [11]= 0 
A[7][2]= 0 [3]= 1 [4]= 0 [10]= 0 [11]= 0 
A[8][2]= 1 [3]=-3 [4]= 1 [10]=-1 [11]=-1 
A[9][2]=-2 [3]=-3 [4]= 1 [10]= 0 [11]= 0 
 depth=0 det= 2 
 pivot  B[6]=8  C[0]=3 
 Basis    0 1 2 5 6 7 8  Row 0 6 5 1 2 3 4 
 Co-Basis 3 4 9 10 11  Column 3 4 2 1 0  det= 2 
A[0][3]= 0 [4]= 0 [9]= 0 [10]= 0 [11]= 0 
A[1][3]= 1 [4]=-1 [9]= 1 [10]= 2 [11]= 2 
A[2][3]=-3 [4]= 1 [9]=-1 [10]= 0 [11]= 0 
A[5][3]= 1 [4]=-1 [9]= 1 [10]= 2 [11]= 2 
A[6][3]=-3 [4]= 1 [9]=-1 [10]= 0 [11]= 0 
A[7][3]= 2 [4]= 0 [9]= 0 [10]= 0 [11]= 0 
A[8][3]=-9 [4]= 3 [9]=-1 [10]=-2 [11]=-2 
 depth=0 det= 9 
 pivot  B[6]=7  C[0]=4 
 Basis    0 1 2 3 5 6 7  Row 0 6 5 4 1 2 3 
 Co-Basis 4 8 9 10 11  Column 4 3 2 1 0  det= 9 
A[0][4]= 0 [8]= 0 [9]= 0 [10]= 0 [11]= 0 
A[1][4]=-3 [8]=-1 [9]= 4 [10]= 8 [11]= 8 
A[2][4]= 0 [8]= 3 [9]=-3 [10]= 3 [11]= 3 
A[3][4]= 3 [8]=-2 [9]=-1 [10]=-2 [11]=-2 
A[5][4]=-3 [8]=-1 [9]= 4 [10]= 8 [11]= 8 
A[6][4]= 0 [8]= 3 [9]=-3 [10]= 3 [11]= 3 
A[7][4]= 3 [8]=-2 [9]=-1 [10]=-2 [11]=-2 
 depth=0 det= 3 
end of first phase of getabasis: lastdv=4 nredundcol=0
redundant cobases:
 Basis    0 1 2 3 4 5 6  Row 0 6 5 4 3 1 2 
 Co-Basis 7 8 9 10 11  Column 4 3 2 1 0  det= 3 
A[0][7]= 0 [8]= 0 [9]= 0 [10]= 0 [11]= 0 
A[1][7]=-3 [8]=-1 [9]= 1 [10]= 2 [11]= 2 
A[2][7]= 0 [8]= 1 [9]=-1 [10]= 1 [11]= 1 
A[3][7]= 3 [8]= 0 [9]= 0 [10]= 0 [11]= 0 
A[4][7]= 9 [8]= 2 [9]= 1 [10]= 2 [11]= 2 
A[5][7]=-3 [8]=-1 [9]= 1 [10]= 2 [11]= 2 
A[6][7]= 0 [8]= 1 [9]=-1 [10]= 1 [11]= 1 

removing cobasic index k=3 C[k]=10
 Basis    0 1 2 3 4 5 6  Row 0 6 5 4 3 1 2 
 Co-Basis 7 8 9 10  Column 1 3 2 0  det= 3 
A[0][7]= 0 [8]= 0 [9]= 0 [10]= 0 
A[1][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[2][7]= 0 [8]= 1 [9]=-1 [10]= 1 
A[3][7]= 3 [8]= 0 [9]= 0 [10]= 0 
A[4][7]= 9 [8]= 2 [9]= 1 [10]= 2 
A[5][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[6][7]= 0 [8]= 1 [9]=-1 [10]= 1 

 Basis    0 1 2 3 4 5 6  Row 0 6 5 4 3 1 2 
 Co-Basis 7 8 9 10  Column 1 3 2 0  det= 3 
A[0][7]= 0 [8]= 0 [9]= 0 [10]= 0 
A[1][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[2][7]= 0 [8]= 1 [9]=-1 [10]= 1 
A[3][7]= 3 [8]= 0 [9]= 0 [10]= 0 
A[4][7]= 9 [8]= 2 [9]= 1 [10]= 2 
A[5][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[6][7]= 0 [8]= 1 [9]=-1 [10]= 1 

after getabasis
 Basis    0 1 2 3 4 5 6  Row 0 6 5 4 3 1 2 
 Co-Basis 7 8 9 10  Column 1 3 2 0  det= 3 
A[0][7]= 0 [8]= 0 [9]= 0 [10]= 0 
A[1][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[2][7]= 0 [8]= 1 [9]=-1 [10]= 1 
A[3][7]= 3 [8]= 0 [9]= 0 [10]= 0 
A[4][7]= 9 [8]= 2 [9]= 1 [10]= 2 
A[5][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[6][7]= 0 [8]= 1 [9]=-1 [10]= 1 

V-representation
begin
***** 5 rational
inequality array initialization: 1 2 3 4 5
 Basis    0 1 2 3 4 5 6  Row 0 6 5 4 3 1 2 
 Co-Basis 7 8 9 10  Column 1 3 2 0  det= 3 
A[0][7]=-3 [8]=-3 [9]=-3 [10]= 0 
A[1][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[2][7]= 0 [8]= 1 [9]=-1 [10]= 1 
A[3][7]= 3 [8]= 0 [9]= 0 [10]= 0 
A[4][7]= 9 [8]= 2 [9]= 1 [10]= 2 
A[5][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[6][7]= 0 [8]= 1 [9]=-1 [10]= 1 

*Inequality numbers for indices 5 .. 9 :  1  2  3  4  5 
 Basis    0 1 2 3 4 5 6  Row 0 6 5 4 3 1 2 
 Co-Basis 7 8 9 10  Column 1 3 2 0  det= 3 
A[0][7]=-3 [8]=-3 [9]=-3 [10]= 0 
A[1][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[2][7]= 0 [8]= 1 [9]=-1 [10]= 1 
A[3][7]= 3 [8]= 0 [9]= 0 [10]= 0 
A[4][7]= 9 [8]= 2 [9]= 1 [10]= 2 
A[5][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[6][7]= 0 [8]= 1 [9]=-1 [10]= 1 

Dictionary resized from d=4 to d=3
 Basis    0 1 2 3 4 5 6  Row 0 6 5 4 3 1 2 
 Co-Basis 7 8 9 10  Column 1 3 2 0  det= 3 
A[0][7]=-3 [8]=-3 [9]=-3 [10]= 0 
A[1][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[2][7]= 0 [8]= 1 [9]=-1 [10]= 1 
A[3][7]= 3 [8]= 0 [9]= 0 [10]= 0 
A[4][7]= 9 [8]= 2 [9]= 1 [10]= 2 
A[5][7]=-3 [8]=-1 [9]= 1 [10]= 2 
A[6][7]= 0 [8]= 1 [9]=-1 [10]= 1 
```

**Comment by oyamad** [comment]
I thought alternatively of redefining the `N` field by `m.N = isa(m, HMatrix) ? getd(m) : getd(m)-1` just after `m.P = Pptr[]` in https://github.com/JuliaPolyhedra/LRSLib.jl/blob/5d819d4a52554dfd69ef26881ad59b15f191e0bd/src/matrix.jl#L358-L382 and https://github.com/JuliaPolyhedra/LRSLib.jl/blob/5d819d4a52554dfd69ef26881ad59b15f191e0bd/src/matrix.jl#L384-L391 but some tests in `test/polyhedron.jl` didn't pass.

**Comment by blegat** [comment]
@oyamad What's the status of this ?

**Comment by oyamad** [comment]
This is ready to merge.

**Comment by blegat** [comment]
Sorry for the delay !

**Pull request merged**
